/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FenetrePrincipale.java
 *
 * Created on 5 avr. 2016, 09:40:57
 */

package pfe2016Gui;

import java.awt.geom.GeneralPath;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import java.awt.geom.Ellipse2D;
import static java.awt.GraphicsDevice.WindowTranslucency.*;

/**
 *
 * @author Madiha
 */
public class FenetrePrincipale extends javax.swing.JFrame {

    /** Creates new form FenetrePrincipale */
    public FenetrePrincipale() {
        super("ShapedWindow");

         // ----------------------------------------------
        // Shape ----------------------------------------

        Graphics2D g2 = (Graphics2D) this.getGraphics();
        // draw GeneralPath (polygon)
        int x1Points[] = {0, 1000, 0, 1000};
        int y1Points[] = {0, 500, 500, 0};
        final GeneralPath polygon =
                new GeneralPath(GeneralPath.WIND_EVEN_ODD,
                                x1Points.length);
        polygon.moveTo(x1Points[0], y1Points[0]);

        for (int index = 1; index < x1Points.length; index++) {
                polygon.lineTo(x1Points[index], y1Points[index]);
        };
        
        /*polygon.moveTo(-a, -a);
        polygon.lineTo(a, a);
        polygon.lineTo(-a, a);
        polygon.lineTo(a, -a);
         */

        /*polygon.moveTo(-a, 0);
        polygon.curveTo(-a, 0, (double)-a/2, (double)-a/2, 0, -a);
        polygon.lineTo(a, -a);
        polygon.lineTo(a, a);
        polygon.lineTo(a, -a);
        polygon.lineTo(-a, 0);
         *
         */
        

        polygon.closePath();
        
        //End Shape --------------------------------------
        
        setLayout(new GridBagLayout());
        addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                setShape(new Ellipse2D.Double(0, 0, getWidth(), getHeight()));
                //setShape(polygon);
            }
        });
        setUndecorated(true);
        setSize(1000, 500);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        add(new JButton("I am a Button"));

        JButton btnClose = new JButton("Close");
        add(btnClose);
        ActionListener al;
        al = new ActionListener() {
            public void actionPerformed(ActionEvent ae) {
                System.exit(0);
            }
        };
        btnClose.addActionListener (al);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        GraphicsDevice gd = ge.getDefaultScreenDevice();

        if (!gd.isWindowTranslucencySupported(TRANSLUCENT)) {
            System.err.println("Translucency is not supported");
            System.exit(0);
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                FenetrePrincipale tw = new FenetrePrincipale();
                tw.setOpacity(0.80f);
                tw.setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
