/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SimpleInterface.java
 *
 * Created on 30 avr. 2016, 00:27:14
 */

package pfe2016Gui;

import analyserDesFichier.AnalyserFichierXML;
import analyserDesFichier.StructurePhrase;
import calculeDeSimilarite.SimilariteOuPolarite;
import java.awt.Color;
import java.io.File;
import java.util.Vector;
import javax.swing.JFileChooser;

/**
 *
 * @author Madiha
 */
public class SimpleInterface extends javax.swing.JFrame {

    // Attributs
    private SimilariteOuPolarite analyseur ;
    private double polariteTexte = 0;
    private double subjectiviteTexte = 0;

    // Pour la Similarité
    private boolean testerSimilarite = true;
    private String cheminDeLaBDDDuCorpusC2;
    private char methodeDeCalculDeSimilarite = 'n';
    private int similariteNgramme = 2;
    private double seuilMinSimilarite = 0.9;

    // Pour la Racinisation
    private boolean utiliserStemmer = true;
    private String methodeDeRacinisation = "khoja";

    // Pour la Traduction
    private boolean utiliserTraduction = true;
    private String traducteur = "ms";

    // Pour l'Arabization
    private boolean utiliserArabization = true;
    private boolean testerRacineArabizi = true;

    // Pour les caractères répétés
    private boolean considererCaracteresRepetes = true;
    private double CaracteresRepetes = 1.5;

    /** Creates new form SimpleInterface */
    public SimpleInterface() {
        initComponents();
        analyseur = new SimilariteOuPolarite();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jFileChooser1 = new javax.swing.JFileChooser();
        jFileChooser2 = new javax.swing.JFileChooser();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Wach t7ass Analyseur de Sentiments développé par B.Madiha & Z.Omar");
        setBackground(new java.awt.Color(0, 153, 153));
        setBounds(new java.awt.Rectangle(400, 200, 500, 200));
        setFont(new java.awt.Font("Gabriola", 0, 14)); // NOI18N
        setForeground(new java.awt.Color(0, 204, 204));
        setResizable(false);

        jTextPane1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 16)); // NOI18N
        jTextPane1.setToolTipText("Ecrivez ce que vous voulez analyser!");
        jTextPane1.setOpaque(false);
        jScrollPane1.setViewportView(jTextPane1);

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Madiha\\Documents\\Spyder_Workspace\\pfe2016Gui\\src\\images\\volume-icon.png")); // NOI18N
        jButton1.setToolTipText("Analyser texte");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jButton1.setDisabledIcon(new javax.swing.ImageIcon("C:\\Users\\Madiha\\Documents\\Spyder_Workspace\\pfe2016Gui\\src\\images\\volume-icon.png")); // NOI18N
        jButton1.setDisabledSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\Madiha\\Documents\\Spyder_Workspace\\pfe2016Gui\\src\\images\\volume-icon.png")); // NOI18N
        jButton1.setFocusPainted(false);
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setPressedIcon(new javax.swing.ImageIcon("C:\\Users\\Madiha\\Documents\\Spyder_Workspace\\pfe2016Gui\\src\\images\\volume-icon.png")); // NOI18N
        jButton1.setRolloverIcon(new javax.swing.ImageIcon("C:\\Users\\Madiha\\Documents\\Spyder_Workspace\\pfe2016Gui\\src\\images\\volume-icon (1).png")); // NOI18N
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Madiha\\Documents\\Spyder_Workspace\\pfe2016Gui\\src\\images\\document-icon.png")); // NOI18N
        jButton2.setToolTipText("Lire fichier");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton2.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jButton2.setDisabledIcon(new javax.swing.ImageIcon("C:\\Users\\Madiha\\Documents\\Spyder_Workspace\\pfe2016Gui\\src\\images\\document-icon.png")); // NOI18N
        jButton2.setDisabledSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\Madiha\\Documents\\Spyder_Workspace\\pfe2016Gui\\src\\images\\document-icon.png")); // NOI18N
        jButton2.setFocusPainted(false);
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setPressedIcon(new javax.swing.ImageIcon("C:\\Users\\Madiha\\Documents\\Spyder_Workspace\\pfe2016Gui\\src\\images\\document-icon.png")); // NOI18N
        jButton2.setRolloverIcon(new javax.swing.ImageIcon("C:\\Users\\Madiha\\Documents\\Spyder_Workspace\\pfe2016Gui\\src\\images\\document-icon (1).png")); // NOI18N
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Madiha\\Documents\\Spyder_Workspace\\pfe2016Gui\\src\\images\\settings-icon.png")); // NOI18N
        jButton3.setToolTipText("Paramètres de l'Analyseur");
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton3.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jButton3.setDisabledIcon(new javax.swing.ImageIcon("C:\\Users\\Madiha\\Documents\\Spyder_Workspace\\pfe2016Gui\\src\\images\\settings-icon.png")); // NOI18N
        jButton3.setDisabledSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\Madiha\\Documents\\Spyder_Workspace\\pfe2016Gui\\src\\images\\settings-icon.png")); // NOI18N
        jButton3.setFocusPainted(false);
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setPressedIcon(new javax.swing.ImageIcon("C:\\Users\\Madiha\\Documents\\Spyder_Workspace\\pfe2016Gui\\src\\images\\settings-icon.png")); // NOI18N
        jButton3.setRolloverIcon(new javax.swing.ImageIcon("C:\\Users\\Madiha\\Documents\\Spyder_Workspace\\pfe2016Gui\\src\\images\\settings-icon (1).png")); // NOI18N
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Madiha\\Documents\\Spyder_Workspace\\pfe2016Gui\\src\\images\\toolbox-icon.png")); // NOI18N
        jButton4.setToolTipText("Charger les lexiques");
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton4.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jButton4.setDisabledIcon(new javax.swing.ImageIcon("C:\\Users\\Madiha\\Documents\\Spyder_Workspace\\pfe2016Gui\\src\\images\\toolbox-icon.png")); // NOI18N
        jButton4.setDisabledSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\Madiha\\Documents\\Spyder_Workspace\\pfe2016Gui\\src\\images\\toolbox-icon.png")); // NOI18N
        jButton4.setFocusPainted(false);
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setPressedIcon(new javax.swing.ImageIcon("C:\\Users\\Madiha\\Documents\\Spyder_Workspace\\pfe2016Gui\\src\\images\\toolbox-icon.png")); // NOI18N
        jButton4.setRolloverIcon(new javax.swing.ImageIcon("C:\\Users\\Madiha\\Documents\\Spyder_Workspace\\pfe2016Gui\\src\\images\\toolbox-icon (1).png")); // NOI18N
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Madiha\\Documents\\Spyder_Workspace\\pfe2016Gui\\src\\images\\chat-icon.png")); // NOI18N
        jButton5.setToolTipText("Nous contacter");
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton5.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jButton5.setDisabledIcon(new javax.swing.ImageIcon("C:\\Users\\Madiha\\Documents\\Spyder_Workspace\\pfe2016Gui\\src\\images\\chat-icon.png")); // NOI18N
        jButton5.setDisabledSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\Madiha\\Documents\\Spyder_Workspace\\pfe2016Gui\\src\\images\\chat-icon.png")); // NOI18N
        jButton5.setFocusPainted(false);
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setPressedIcon(new javax.swing.ImageIcon("C:\\Users\\Madiha\\Documents\\Spyder_Workspace\\pfe2016Gui\\src\\images\\chat-icon.png")); // NOI18N
        jButton5.setRolloverIcon(new javax.swing.ImageIcon("C:\\Users\\Madiha\\Documents\\Spyder_Workspace\\pfe2016Gui\\src\\images\\chat-icon (1).png")); // NOI18N
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Madiha\\Documents\\Spyder_Workspace\\pfe2016Gui\\src\\images\\easel-icon.png")); // NOI18N
        jButton6.setToolTipText("Visualiser résultats ");
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton6.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jButton6.setDisabledIcon(new javax.swing.ImageIcon("C:\\Users\\Madiha\\Documents\\Spyder_Workspace\\pfe2016Gui\\src\\images\\easel-icon.png")); // NOI18N
        jButton6.setDisabledSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\Madiha\\Documents\\Spyder_Workspace\\pfe2016Gui\\src\\images\\easel-icon.png")); // NOI18N
        jButton6.setEnabled(false);
        jButton6.setFocusPainted(false);
        jButton6.setFocusable(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setPressedIcon(new javax.swing.ImageIcon("C:\\Users\\Madiha\\Documents\\Spyder_Workspace\\pfe2016Gui\\src\\images\\easel-icon.png")); // NOI18N
        jButton6.setRolloverIcon(new javax.swing.ImageIcon("C:\\Users\\Madiha\\Documents\\Spyder_Workspace\\pfe2016Gui\\src\\images\\easel-icon (1).png")); // NOI18N
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Felix Titling", 1, 12));
        jTextField1.setEnabled(false);
        jTextField1.setOpaque(false);
        jTextField1.setSelectionColor(new java.awt.Color(0, 204, 255));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Felix Titling", 1, 12));
        jTextField2.setEnabled(false);
        jTextField2.setOpaque(false);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Felix Titling", 1, 12));
        jTextField3.setEnabled(false);
        jTextField3.setOpaque(false);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("Felix Titling", 1, 12));
        jTextField4.setEnabled(false);
        jTextField4.setOpaque(false);
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setBorderPainted(false);
        jMenuBar1.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N

        jMenu1.setText("Fichier");
        jMenu1.setFont(new java.awt.Font("Mangal", 0, 12));
        jMenu1.setRolloverIcon(new javax.swing.ImageIcon("C:\\Users\\Madiha\\Documents\\Spyder_Workspace\\pfe2016Gui\\src\\images\\document-icon (1).png")); // NOI18N
        jMenu1.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\Madiha\\Documents\\Spyder_Workspace\\pfe2016Gui\\src\\images\\document-icon.png")); // NOI18N

        jMenuItem1.setText("Lire fichier texte");
        jMenu1.add(jMenuItem1);

        jMenuItem14.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem14.setText("Lire fichier XML");
        jMenu1.add(jMenuItem14);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Analyse");
        jMenu2.setFont(new java.awt.Font("Mangal", 0, 12));
        jMenu2.setRolloverIcon(new javax.swing.ImageIcon("C:\\Users\\Madiha\\Documents\\Spyder_Workspace\\pfe2016Gui\\src\\images\\document-icon (1).png")); // NOI18N

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        jMenuItem3.setText("Analyser le texte");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Visualiser les résultats");
        jMenu2.add(jMenuItem4);
        jMenu2.add(jSeparator1);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Configuration");
        jMenu3.setFont(new java.awt.Font("Mangal", 0, 12));
        jMenu3.setRolloverIcon(new javax.swing.ImageIcon("C:\\Users\\Madiha\\Documents\\Spyder_Workspace\\pfe2016Gui\\src\\images\\document-icon (1).png")); // NOI18N
        jMenu3.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\Madiha\\Documents\\Spyder_Workspace\\pfe2016Gui\\src\\images\\document-icon.png")); // NOI18N

        jMenuItem5.setText("Racinisation");
        jMenu3.add(jMenuItem5);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setText("Traduction");
        jMenu3.add(jMenuItem6);

        jMenuItem12.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem12.setText("Arabization");
        jMenu3.add(jMenuItem12);

        jMenuItem13.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem13.setText("Traitement des caractères répétés");
        jMenu3.add(jMenuItem13);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Ressources");
        jMenu4.setFont(new java.awt.Font("Mangal", 0, 12));
        jMenu4.setRolloverIcon(new javax.swing.ImageIcon("C:\\Users\\Madiha\\Documents\\Spyder_Workspace\\pfe2016Gui\\src\\images\\document-icon (1).png")); // NOI18N

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem7.setText("Lexiques");
        jMenu4.add(jMenuItem7);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem8.setText("Corpus");
        jMenu4.add(jMenuItem8);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("A propos");
        jMenu5.setFont(new java.awt.Font("Mangal", 0, 12));
        jMenu5.setRolloverIcon(new javax.swing.ImageIcon("C:\\Users\\Madiha\\Documents\\Spyder_Workspace\\pfe2016Gui\\src\\images\\document-icon (1).png")); // NOI18N
        jMenu5.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\Madiha\\Documents\\Spyder_Workspace\\pfe2016Gui\\src\\images\\document-icon.png")); // NOI18N

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem9.setText("License GNU GPL");
        jMenu5.add(jMenuItem9);

        jMenuItem10.setText("Nous contacter sur Github");
        jMenu5.add(jMenuItem10);

        jMenuItem11.setText("Nous contacter sur Sourceforge");
        jMenu5.add(jMenuItem11);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField4)
                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jTextField2.setText("");
        jTextField4.setText("");
        analyseur.LancerLeCalcul(this.jTextPane1.getText(), 'n', 2);
        polariteTexte = analyseur.getPolarite();
        subjectiviteTexte = analyseur.getSubjectivite();
        jTextField1.enable();
        jTextField2.enable();
        jTextField3.enable();
        jTextField4.enable();

        jTextField1.setText("La subjectivité est estimée à :");
        jTextField3.setText("La polarité est estimée à :");
        if (polariteTexte<0)
            jTextField4.setForeground(Color.decode("#FF0500"));
        else
            jTextField4.setForeground(Color.decode("#00A000"));
        jTextField4.setText(polariteTexte+".");

        if (subjectiviteTexte>=0.5)
            jTextField2.setForeground(Color.blue);
        else
            jTextField2.setForeground(Color.decode("#FF6000"));
        jTextField2.setText(subjectiviteTexte*100+"%.");
        jButton6.setEnabled(true);
}//GEN-LAST:event_jButton1ActionPerformed

    boolean estUnFichierXML(String cheminDuFichier){
        return true;
    }

    boolean estUnFichierTxt(String cheminDuFichier){
        return true;
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int ret = jFileChooser1.showOpenDialog(null);
        if (ret== JFileChooser.APPROVE_OPTION)
        {
            File fichier = jFileChooser1.getSelectedFile();
            String cheminDuFichier= fichier.getAbsolutePath();
            System.out.println(cheminDuFichier);
            // Analyser un fichier XML
            if (estUnFichierXML(cheminDuFichier)){
                AnalyserFichierXML analyseur = new AnalyserFichierXML(cheminDuFichier,
                                                                      testerSimilarite,
                                                                      cheminDeLaBDDDuCorpusC2,
                                                                      seuilMinSimilarite,
                                                                      utiliserStemmer,
                                                                      methodeDeRacinisation,
                                                                      utiliserTraduction,
                                                                      traducteur,
                                                                      utiliserArabization,
                                                                      testerRacineArabizi,
                                                                      considererCaracteresRepetes
                                                                      );
                analyseur.analyserFichier(methodeDeCalculDeSimilarite, similariteNgramme);
                Vector<StructurePhrase> phrases = new Vector<StructurePhrase>();
                phrases = analyseur.getPhrases();
            }
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        analyseur.LancerLeCalcul(this.jTextPane1.getText(), 'n', 2);
        polariteTexte = analyseur.getPolarite();
        subjectiviteTexte = analyseur.getSubjectivite();
        jTextField1.enable();
        jTextField2.enable();
        jTextField3.enable();
        jTextField4.enable();

        jTextField1.setText("La subjectivité est estimée à :");
        jTextField3.setText("La polarité est estimée à :");
        if (polariteTexte<0)
            jTextField4.setForeground(Color.decode("#FF0500"));
        else
            jTextField4.setForeground(Color.decode("#00A000"));
        jTextField4.setText(polariteTexte+".");

        if (subjectiviteTexte>=0.5)
            jTextField2.setForeground(Color.blue);
        else
            jTextField2.setForeground(Color.decode("#FF6000"));
        jTextField2.setText(subjectiviteTexte*100+"%.");
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SimpleInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JFileChooser jFileChooser2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables

}
